### ISSUE TITLE
AWS Lambada Runtime API

### ISSUE THREAD

**Issue by Prince2k3** [choefele/swift-lambda-app#4]
Do you plan on getting this working with the new AWS Runtime Lambda API instead of using shim with nodeJS?

**Comment by maximveksler** [comment]
@Prince2k3 actually - any thoughts on this?

**Comment by Prince2k3** [comment]
This repo seems to be doing somethings with SwiftNIO and AWS Lambda
@maximveksler https://github.com/swift-sprinter/aws-lambda-swift-sprinter
